### PR TITLE
[svsim] Avoid EndOfMessages Exception

### LINKED ISSUE #4700: [Chiselsim] Exit simulation on $finish
Currently, Chiselsim will only terminate if the simulator exits or the commands that it is trying to run are done. However, different simulators handle things like `$finish` (which the Chisel `stop` API lowers to) differently. E.g., consider the following example code:

``` verilog
module Foo();

initial begin
  $display("hello");
  $finish;
  $display("world");
  $finish;
end

endmodule
```

Compiling this with Verilator (`verilator --binary Foo.sv && ./obj_dir/VFoo`) will produce:

```
hello
- Foo.sv:5: Verilog $finish
world
- Foo.sv:7: Verilog $finish
```

If you run this with VCS (`vcs Foo.sv && ./simv`) will produce:

```
hello
$finish called from file "Foo.sv", line 5.
$finish at simulation time                    0
```

The problem here is that Verilator doesn't terminate. This seems to violate the Verilog spec, based on the snippet below:

Image

That said, we can work around this by querying the `VerilatedContext.getFinish()` member function when in the `run_simulation` function (or elsewhere) to see if Verilator is reporting that the simulation is done.

This has two major benefits:

1. Simulations will actually exit instead of running until they hit a timeout. For `ChiselSpec`, this is currently 10k half-periods. We can exit simulations way earlier without wasting cycles.
2. [We are hacking around this by post-processing the log looking for finish _before_ an assert.](https://github.com/chipsalliance/chisel/blob/main/src/test/scala-2/chiselTests/ChiselSpec.scala#L104) All that checking logic can just go away if simulations actually terminate.

### PR DESCRIPTION
**Pull request by seldridge**
Add a `final` block to svsim's Verilog which will call a DPI function to finish the simulation.  This causes the simulator to either exit (if a done command has been received) or wait until it sees _excatly_ a done command.

Because of the different ways that simulators can choose to implement time delays, the simulator _may_ have outstanding transactions that need to be finished.  Finish any outstanding transactions before blocking on a done command.  Use this new outstanding transaction state to implement the old `receivedDone` state.

This is done to get equivalent behavior between Verilator and VCS when a Verilog `$finish` is executed.

#### Release Notes

- Rework svsim to use a `final` block that will finish any outstanding transactions. This fixes a class of bugs where VCS simulations could generate `UnexpectedEndOfMessages` exceptions and need to be caught by the user. This fixes #4700 for VCS.

### CODE REVIEW

File: svsim/src/main/resources/simulation-driver.cpp [hunk 1]
```diff
@@ -769,29 +795,25 @@ static void processCommand() {
...
-      }
+      run_simulation(timestepsPerPhase, &finish);
+      if (finish)
+        return true;
     }
 
-    cycles--; // Consume the unbalanced increment from the while condition
-    sendUintAsBits(cycles);
+    // Consume the unbalanced increment from the while condition
+    sendUintAsBits(--cycles);
```
Comment (jackkoenig) [inline svsim/src/main/resources/simulation-driver.cpp:808]: Is it really worth merging these into one line?

Comment (seldridge) [reply svsim/src/main/resources/simulation-driver.cpp:808]: I tend to like this terseness. However, I can see it being confusing.

Note: the more important change here is a change from postincrement to preincrement. This, doesn't make a difference here at all, however, I've gotten the [LLVM Coding Guidelines which basically says "never use postincrement"](https://llvm.org/docs/CodingStandards.html#prefer-preincrement) beaten into me through code reviews I will always convert something to preincrement when I see it. (Again, this doesn't make a difference as postincrement isn't slow for primitive types, but it's annoying to remember when postincrement could be expensive, so LLVM just banned it.)

After making the postincrement to preincrement change this can then be inlined and I will tend to inline anything single use (which I realize is different from others which prefer things broken out).
