### PR TITLE
PeekPokeAPI: include source location on failed expect() calls.

### LINKED ISSUE #4128: PeekPokeAPI expectations don't return the actual test line (or I'm getting it very wrong)
Hi all! I'm using ChiselSim with Chisel 6.4.0. The actual tests test fine, but when an expectation fails, I sometimes find it hard to debug, except by adding loads of additional `message` arguments. For a concrete example:

```scala
it should "transmit a command packet" in {
  simulate(new SPI) { c =>
    c.reset.poke(true.B)
    c.clock.step()
    c.reset.poke(false.B)

    c.clock.step()
    c.io.req.ready.expect(true.B)

    c.io.req.bits.cmd.poke(0x19.U)
    c.io.req.bits.cmdRem.poke(0.U)
    c.io.req.bits.respLen.poke(0.U)
    c.io.req.valid.poke(true.B)

    c.clock.step()

    c.io.req.ready.expect(false.B)
  }
}
```

I haven't actually implemented any non-initial state yet, so I expect the final line to fail. And it does, but the spec file itself only gets a mention for the line with the `simulate` call (line 17 in this case). The full output is long, so it's hidden below.

<details><summary>`sbt test` output with `-oF` added to the test options</summary>

```sbt
sbt:ili9341spi> test
[info] SPISpec:
[info] SPI
[info] - should transmit a command packet *** FAILED ***
[info]   chisel3.simulator.PeekPokeAPI$FailedExpectationException: Failed Expectation: Observed value '1' != 0. Expectation failed: observed value 1 != 0
[info]   at chisel3.simulator.PeekPokeAPI$testableData.$anonfun$expect$9(PeekPokeAPI.scala:135)
[info]   at chisel3.simulator.PeekPokeAPI$testableData.$anonfun$expect$9$adapted(PeekPokeAPI.scala:133)
[info]   at svsim.Simulation$Port$$anonfun$check$1.applyOrElse(Simulation.scala:426)
[info]   at svsim.Simulation$Port$$anonfun$check$1.applyOrElse(Simulation.scala:424)
[info]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[info]   at svsim.Simulation$Controller.$anonfun$completeInFlightCommands$1(Simulation.scala:195)
[info]   at svsim.Simulation$Controller.$anonfun$completeInFlightCommands$1$adapted(Simulation.scala:192)
[info]   at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
[info]   at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
[info]   at svsim.Simulation$Controller.completeInFlightCommands(Simulation.scala:192)
[info]   at chisel3.simulator.package$AnySimulatedModule.completeSimulation(package.scala:56)
[info]   at chisel3.simulator.Simulator.$anonfun$_simulate$1(Simulator.scala:112)
[info]   at chisel3.simulator.package$ChiselSimulation.$anonfun$runElaboratedModule$2(package.scala:97)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[info]   at chisel3.simulator.package$AnySimulatedModule$.withValue(package.scala:81)
[info]   at chisel3.simulator.package$ChiselSimulation.$anonfun$runElaboratedModule$1(package.scala:97)
[info]   at svsim.Simulation.$anonfun$run$3(Simulation.scala:51)
[info]   at scala.util.Try$.apply(Try.scala:210)
[info]   at svsim.Simulation.run(Simulation.scala:50)
[info]   at chisel3.simulator.package$ChiselSimulation.runElaboratedModule(package.scala:94)
[info]   at chisel3.simulator.Simulator$WorkspaceCompiler.$anonfun$process$1(Simulator.scala:64)
[info]   at scala.util.Try$.apply(Try.scala:210)
[info]   at chisel3.simulator.Simulator$WorkspaceCompiler.liftedTree1$1(Simulator.scala:64)
[info]   at chisel3.simulator.Simulator$WorkspaceCompiler.process(Simulator.scala:53)
[info]   at chisel3.simulator.SingleBackendSimulator.processBackends(Simulator.scala:139)
[info]   at chisel3.simulator.SingleBackendSimulator.processBackends$(Simulator.scala:138)
[info]   at chisel3.simulator.EphemeralSimulator$DefaultSimulator.processBackends(EphemeralSimulator.scala:28)
[info]   at chisel3.simulator.Simulator._simulate(Simulator.scala:116)
[info]   at chisel3.simulator.Simulator._simulate$(Simulator.scala:97)
[info]   at chisel3.simulator.EphemeralSimulator$DefaultSimulator._simulate(EphemeralSimulator.scala:28)
[info]   at chisel3.simulator.SingleBackendSimulator.simulate(Simulator.scala:146)
[info]   at chisel3.simulator.SingleBackendSimulator.simulate$(Simulator.scala:142)
[info]   at chisel3.simulator.EphemeralSimulator$DefaultSimulator.simulate(EphemeralSimulator.scala:28)
[info]   at chisel3.simulator.EphemeralSimulator$.simulate(EphemeralSimulator.scala:25)
[info]   at ee.kivikakk.ili9341spi.spi.SPISpec.$anonfun$new$1(SPISpec.scala:17)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1832)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1686)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1830)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1842)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1842)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1824)
[info]   at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1686)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1900)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1900)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1899)
[info]   at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1686)
[info]   at org.scalatest.Suite.run(Suite.scala:1114)
[info]   at org.scalatest.Suite.run$(Suite.scala:1096)
[info]   at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1686)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1945)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1945)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1943)
[info]   at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1686)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:153)
[info]   at sbt.TestRunner.run(TestFramework.scala:168)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:336)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:296)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:336)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:336)
[info]   at sbt.TestFunction.apply(TestFramework.scala:348)
[info]   at sbt.Tests$.$anonfun$toTask$1(Tests.scala:436)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:47)
[info]   at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[info]   at sbt.Execute.work(Execute.scala:292)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[info]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[info]   at java.base/java.lang.Thread.run(Thread.java:1583)
[info] Run completed in 3 seconds, 242 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]         ee.kivikakk.ili9341spi.spi.SPISpec
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed Jun 2, 2024, 4:12:17 PM
sbt:ili9341spi>
```

</details>

```sbt
sbt:ili9341spi> lastGrep SPISpec test
[debug] Running TaskDef(ee.kivikakk.ili9341spi.spi.SPISpec, org.scalatest.tools.Framework$$anon$1@309d642a, false, [SuiteSelector])
[info] SPISpec:
[info]   at ee.kivikakk.ili9341spi.spi.SPISpec.$anonfun$new$1(SPISpec.scala:17)
[error]         ee.kivikakk.ili9341spi.spi.SPISpec
sbt:ili9341spi>
```

I'm sure this is hard to avoid because `expect` is probably just enqueuing the expectation until the sim runtime next goes back to talk to the simulator. (Or something — I haven't looked into how it works at all, other than seeing that such a flow is possible!)

I guess it'd be nice to also capture `SourceInfo` when doing an `expect`, and to report it with any failures? Any thoughts, or if I'm missing something big?

### PR DESCRIPTION
**Pull request by kivikakk**
Fixes #4128. (cc @jackkoenig)

Some notes:

* b3fca5e adds the `SourceInfo` collection and reporting in the exception.
  * I haven't tried stack trace collection. Other than simply not getting to it yet, I don't think I have a rigorous enough setup (or a large enough testcase, which I have a working build going for) to meaningfully assess the performance cost.
  * Minor API design question: do we ever expect `testableData.expect` (with `expected`, `encode` and `buildMessage` arguments) to be called by a test user directly? If not, I have a slight preference for making the `sourceInfo` argument non-implicit there, and only having it implicit in the user-facing calls on `SimulationData`.
* 2d58c7e adds a baseline testcase that `expect()` actually does anything. This isn't specific to this work.
* In f507170, I try a very simple refactor of the source line collection in `ErrorLog`, and use it to embellish the exception.
  * It's not very pretty — I just nyonk `getErrorLineInFile` over to `ExceptionHelpers` and mark it `private[chisel3]` so it doesn't become a new public API to maintain. We have to take `sourceRoots` as an argument.
  * I couldn't actually find a meaningful way to collect source roots at the point of calling `expect()` (no `Builder` context, etc., so I'm not sure how to get at the `ChiselOptions` for a given module, if it's even possible), so we just use none, which defaults to `Seq(new File("."))`. This works fine for Chisel's own test cases and mine in my testing, but maybe there's more complicated setups out there.
  * I also add some very primitive and somewhat brittle checks to the test case added in the previous commit.

I'm not emotionally wed to any of this, so do feel free to suggest other ways for it to be done, or to rework it yourself if that's less overall work! (Particularly thinking of the refactor here, as it's not the cleanest.)

It does work nicely, though:

```
[info] UARTSpec:
[info] UART
[info] - should receive a byte *** FAILED ***
[info]   chisel3.simulator.PeekPokeAPI$FailedExpectationException: Failed Expectation: Observed value '1' != 0. Expectation failed: observed value 1 != 0 @[src/test/scala/ee/hrzn/athena/uart/UARTSpec.scala 64:29]
[info]         c.io.rx.valid.expect(false.B)
[info]                             ^
[info]   at chisel3.simulator.PeekPokeAPI$testableData.$anonfun$expect$9(PeekPokeAPI.scala:157)
[info]   at chisel3.simulator.PeekPokeAPI$testableData.$anonfun$expect$9$adapted(PeekPokeAPI.scala:147)
[info]   at svsim.Simulation$Port$$anonfun$check$1.applyOrElse(Simulation.scala:434)
[info]   at svsim.Simulation$Port$$anonfun$check$1.applyOrElse(Simulation.scala:432)
[info]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[info]   at svsim.Simulation$Controller.$anonfun$completeInFlightCommands$1(Simulation.scala:203)
[info]   at svsim.Simulation$Controller.$anonfun$completeInFlightCommands$1$adapted(Simulation.scala:200)
[info]   at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
[info]   at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
[info]   ...
```

### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
  - The only relevant documentation appears to be the "Migrating from ChiselTest" page, but there's not anything to add here really.
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Feature (or new API)
  - -ish. Simulator debugging info improvement. 
- Internal or build-related (includes code refactoring/cleanup)

#### Desired Merge Strategy

- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

#### Release Notes

`SimulationData.expect` calls now record source location and report it in the `FailedExpectationException` on failure.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.6.x`, `5.x`, or `6.x` depending on impact, API modification or big change: `7.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

File: src/test/scala/chiselTests/simulator/SimulatorSpec.scala [hunk 1]
```diff
@@ -71,6 +71,29 @@ class SimulatorSpec extends AnyFunSpec with Matchers {
...
+          gcd.io.loadValues.poke(0.B)
+          gcd.clock.step(10)
+          gcd.io.result.expect(5)
+        }.result
+      }
+      thrown.getMessage must include regex "Observed value '12' != 5\\."
+      thrown.getMessage must include regex " @\\[src/test/scala/chiselTests/simulator/SimulatorSpec\\.scala \\d+:\\d+\\]"
+      thrown.getMessage must include regex "gcd\\.io\\.result\\.expect\\(5\\)"
+      // Not actually anchoring this so it's not extremely brittle, only somewhat.
+      thrown.getMessage must include regex "                    \\^"
```
Comment (jackkoenig) [inline src/test/scala/chiselTests/simulator/SimulatorSpec.scala:94]:
```suggestion
      thrown.getMessage must include("Observed value '12' != 5.")
      thrown.getMessage must include regex """ @\[src/test/scala/chiselTests/simulator/SimulatorSpec\.scala \d+:\d+\]"""
      thrown.getMessage must include("gcd.io.result.expect(5)")
      // Not actually anchoring this so it's not extremely brittle, only somewhat.
      thrown.getMessage must include("                    ^")
```

Very minor nits, but don't bother with regex when regular String include will do since it's more readable, and I also personally like using triple quotes for regex since I find having to escape `\` in regular Strings to build regexes unreadable.

File: src/main/scala/chisel3/simulator/PeekPokeAPI.scala [hunk 2]
```diff
@@ -126,13 +133,25 @@ trait PeekPokeAPI {
       expected:     T,
       encode:       (Simulation.Value) => T,
       buildMessage: (T, T) => String
+    )(
+      implicit sourceInfo: SourceInfo
```
Comment (jackkoenig) [inline src/main/scala/chisel3/simulator/PeekPokeAPI.scala:137]:
```suggestion
     sourceInfo: SourceInfo
```
> Minor API design question: do we ever expect testableData.expect (with expected, encode and buildMessage arguments) to be called by a test user directly? If not, I have a slight preference for making the sourceInfo argument non-implicit there, and only having it implicit in the user-facing calls on SimulationData.

I agree with your assessment, this isn't really a user API so it should be explicit. However, it is a public API that power users could be using to implement their own peek/poke/expect API, so on backport, we can do a deprecation of the old API.

File: src/main/scala/chisel3/simulator/PeekPokeAPI.scala [hunk 3]
```diff
@@ -3,11 +3,18 @@ package chisel3.simulator
...
 
 trait PeekPokeAPI {
-  case class FailedExpectationException[T](observed: T, expected: T, message: String)
-      extends Exception(s"Failed Expectation: Observed value '$observed' != $expected. $message")
+  case class FailedExpectationException[T](sourceInfo: SourceInfo, extraContext: Seq[String], observed: T, expected: T, message: String)
+      extends Exception(
+        s"Failed Expectation: Observed value '$observed' != $expected. " +
+        s"$message ${sourceInfo.makeMessage(x => x)}" +
+        (if (extraContext.nonEmpty) s"\n${extraContext.mkString("\n")}" else "")
+      )
```
Comment (jackkoenig) [inline src/main/scala/chisel3/simulator/PeekPokeAPI.scala:17]:
```suggestion
  case class FailedExpectationException[T](observed: T, expected: T, message: String)
      extends Exception(s"Failed Expectation: Observed value '$observed' != $expected. $message")
  object FailedExpectationException {
    def apply[T](observed: T, expected: T, message: String, sourceInfo: SourceInfo, extraContext: Seq[String]): FailedExpectationException[T] = {
      val fullMessage =. s"$message ${sourceInfo.makeMessage(x => x)}" +
        (if (extraContext.nonEmpty) s"\n${extraContext.mkString("\n")}" else "")
      new FailedExpectationException(observed, expected, fullMessage)
    }
  }
```
This is minor, but this is a public API and while I don't particularly care for it being public, we should try to maintain it if possible and it's easy enough to do in this case by just adding a factory method. Note I also arbitrarily changed the argument order to an order that makes more sense to me 🤷‍♀️

**Review by jackkoenig — COMMENTED** [review]
This is a fantastic PR, thank you! 

I have left a few minor/nitty comments, please address and I will merge!

> I haven't tried stack trace collection. Other than simply not getting to it yet, I don't think I have a rigorous enough setup (or a large enough testcase, which I have a working build going for) to meaningfully assess the performance cost.

I don't see any reason to bother, this is great.

> I try a very simple refactor of the source line collection in ErrorLog, and use it to embellish the exception. It's not very pretty — I just nyonk getErrorLineInFile over to ExceptionHelpers and mark it private[chisel3] so it doesn't become a new public API to maintain. We have to take sourceRoots as an argument.

I would have done the exact same thing so LGTM

> I couldn't actually find a meaningful way to collect source roots at the point of calling expect() (no Builder context, etc., so I'm not sure how to get at the ChiselOptions for a given module, if it's even possible), so we just use none, which defaults to Seq(new File(".")). This works fine for Chisel's own test cases and mine in my testing, but maybe there's more complicated setups out there.

Yeah it would be nice if we could extract that information from the Builder context, but that requires a larger effort of propagating that info from Chisel elaboration to ChiselSim that's way beyond the scope of this PR. This particular issue probably also doesn't come up very often, and in those cases, they will still get the source locator even if they don't get the source line and carat.

**Comment by jackkoenig** [comment]
Note this is failing formatting which you can run with `./mill __.reformat` (see bottom of `CONTRIBUTING.md`, file is a bit dated but that command at least is correct!).

File: src/main/scala/chisel3/simulator/PeekPokeAPI.scala (hunk 3 above)
Comment (kivikakk) [reply src/main/scala/chisel3/simulator/PeekPokeAPI.scala:17]: This is much cleaner, thanks!

And yeah — I emulated the IR nodes having sourceInfo first, but for an exception like this it probably makes more sense having the expectations first and context after!

**Comment by jackkoenig** [comment]
> Thanks for pointing that out! I just got started with Scala a month ago or so and I've been very slowly exposing myself to the toolchain; Mill is one I've been deferring on (until now!).

It doesn't help that we are in the process of slowly switching from SBT to mill so like 80% of things in this repo are still using SBT but a couple of things are using Mill 🙃

**Review by jackkoenig — APPROVED** [review]
Thank you!
