### PR TITLE
fix: wrap all intrinsics in layerblocks

### LINKED ISSUE #4429: [FIRRTL] LTL intrinsics are out of the verification layer block
**Type of issue**: Bug Report

There are two problems here: 
First, properties generates LTL intrinsics that are outside the Verification layer block.
Second, the above behavior will cause a firtool error `verification operation used in a non-verification context`, which only occurs in specific cases that I have not figured out, and I will provide a minial example to reproduce below.

**Please provide the steps to reproduce the problem:**

```scala
AssumeProperty(
  inputNotValid |=> not(inputFire),
  label = Some("GCD_ASSUMPTION_INPUT_NOT_VALID")
)
```
This Scala code generates the following FIRRTL:

```firrtl
node not = intrinsic(circt_ltl_not : UInt<1>, _T)
node delay = intrinsic(circt_ltl_delay<delay = 1, length = 0> : UInt<1>, UInt<1>(0h1))
node concat = intrinsic(circt_ltl_concat : UInt<1>, _T_5, delay)
node implication = intrinsic(circt_ltl_implication : UInt<1>, concat, not)
node x4_has_been_reset = intrinsic(circt_has_been_reset : UInt<1>, clock, reset)
node x4 = eq(x4_has_been_reset, UInt<1>(0h0))
layerblock Verification :
  layerblock Assume :
    node clock_1 = intrinsic(circt_ltl_clock :
    node _T_6 = eq(x4, UInt<1>(0h0))
    intrinsic(circt_verif_assume<label = "GCD_ASSUMPTION_INPUT_NOT_VALID">, clock_1, _T_6)
```

which works fine with firtool, although I think the intrinsics should be inside the layerblock.

However, this Scala code that just adds another property will break the firtool:

```scala
AssumeProperty(
  inputNotValid |=> not(inputFire),
  label = Some("GCD_ASSUMPTION_INPUT_NOT_VALID")
)

AssertProperty(
  inputFire |=> inputNotFire.repeatAtLeast(1) ### outputFire,
  label = Some("GCD_ALWAYS_RESPONSE")
)
```

The diff tool tells me that the difference between the two firrtl is only the extra property but firtool encounters this error:

```
gcd/src/GCDFormal.scala:68:19: error: verification operation used in a non-verification context
    inputNotValid |=> not(inputFire),
                  ^
gcd/src/GCDFormal.scala:68:19: note: see current operation: %10 = "ltl.delay"(%1) {delay = 1 : i64, length = 0 : i64} : (i1) -> !ltl.sequence
gcd/src/GCDFormal.scala:72:17: note: leaking outside verification context here
  AssertProperty(
                ^
```

The full firrtl files are here:

[good.fir](http://fars.ee/Sf-_)
[bad.fir](http://fars.ee/QI5_)

### PR DESCRIPTION
**Pull request by unlsycn**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

This PR is based on #4436 and fixes #4429.

#### Type of Improvement

- Feature (or new API)

#### Desired Merge Strategy

- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

#### Release Notes

Fix LTL intrinsics are generated outside the verification layer block

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.6.x`, `5.x`, or `6.x` depending on impact, API modification or big change: `7.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

File: src/main/scala/chisel3/ltl/LTL.scala [hunk 1]
```diff
@@ -408,7 +408,7 @@ sealed abstract class AssertPropertyLike(defaultLayer: Layer) {
     *   emitted as `label: assert(...)`.
     */
   def apply(
-    prop:    Property,
+    prop:    => Property,
```
Comment (sequencer) [inline src/main/scala/chisel3/ltl/LTL.scala:411]: Interesting fixup. LGTM

**Review by sequencer — APPROVED** [review]
Wait for #4436, this fix lgtm.

File: src/main/scala/chisel3/ltl/LTL.scala (hunk 1 above)
Comment (jackkoenig) [reply src/main/scala/chisel3/ltl/LTL.scala:411]: Why is this change here? If you look below, `prop` is accessed multiple times so now this is going to execute multiple times.

**Review by jackkoenig — CHANGES_REQUESTED** [review]

File: src/main/scala/chisel3/ltl/LTL.scala (hunk 1 above)
Comment (unlsycn) [reply src/main/scala/chisel3/ltl/LTL.scala:411]: It is intended to delay `prop` to be evaluated in the `block`. Actually, it will only execute once since the definition of `fold` is
```scala
@inline final def fold[B](ifEmpty: => B)(f: A => B): B =
  if (isEmpty) ifEmpty else f(this.get)
```

Comment (jackkoenig) [reply src/main/scala/chisel3/ltl/LTL.scala:411]: Good point and very clever, perhaps too clever 🙂. This was not obvious to me (despite the fact that I should know better), so I suspect it won't be obvious to others in the future updating this code. So in the interest of defensive programming against future bugs, please create a val above `val clocked` (but obviously inside the `block` that you assign `prop` to with a comment saying "evaluate by name parameter once", and then use that value in the `fold`.

**Review by jackkoenig — APPROVED** [review]
Nice!

File: src/main/scala/chisel3/ltl/LTL.scala (hunk 1 above)
Comment (unlsycn) [reply src/main/scala/chisel3/ltl/LTL.scala:411]: Thank you for the suggestion.
