### PR TITLE
Partial fix for probe and Decoupled interaction + demo of workaround

### LINKED ISSUE #3556: Incorrect FIRRTL for BoringUtils upwards read
If you use `BoringUtils.tap` or `BoringUtils.tapAndRead` that results in an upwards reference, this will create an input port that does not have flips stripped.  This results in illegal FIRRTL and will error out in CIRCT.

Example:

```scala
//> using scala "2.13.11"
//> using lib "org.chipsalliance::chisel::6.0.0-M3"
//> using plugin "org.chipsalliance:::chisel-plugin::6.0.0-M3"
//> using options "-unchecked", "-deprecation", "-language:reflectiveCalls", "-feature", "-Xcheckinit", "-Xfatal-warnings", "-Ywarn-dead-code", "-Ywarn-unused", "-Ymacro-annotations"

import chisel3._
import chisel3.util.{Decoupled, DecoupledIO}
import chisel3.util.experimental.BoringUtils
import circt.stage.ChiselStage

class Bar(b: DecoupledIO[Bool]) extends RawModule {
  BoringUtils.tapAndRead(b)
}

class Foo extends RawModule {
  val a = WireInit(Decoupled(Bool()), DontCare)
  dontTouch(a)

  val bar = Module(new Bar(a))
}

object Main extends App {
  println(
    ChiselStage.emitCHIRRTL(new Foo)
  )
  println(
    ChiselStage.emitSystemVerilog(
      gen = new Foo,
      firtoolOpts = Array("-disable-all-randomization", "-strip-debug-info")
    )
  )
}
```

This produces (`scala-cli Foo.scala`) the following CHIRRTL:

```
FIRRTL version 3.1.0
circuit Foo :%[[
  {
    "class":"firrtl.transforms.DontTouchAnnotation",
    "target":"~Foo|Foo>a"
  }
]]
  module Bar :
    input bore : { flip ready : UInt<1>, valid : UInt<1>, bits : UInt<1>}snippets/BoringUtils.scala 12:25]

    skip

  module Foo :

    wire a : { flip ready : UInt<1>, valid : UInt<1>, bits : UInt<1>}snippets/BoringUtils.scala 16:19]
    invalidate a.bits
    invalidate a.valid
    invalidate a.ready
    inst bar of Bar
    connect bar.bore, a
```

The error produced during FIRRTL compilation is:

```
Exception in thread "main" circt.stage.phases.Exceptions$FirtoolNonZeroExitCode: firtool returned a non-zero exit code. Note that this version of Chisel (6.0.0-M3) was published against firtool version 1.52.0.
------------------------------------------------------------------------------
ExitCode:
1
STDOUT:

STDERR:
<unknown>:0: warning: option -dedup is deprecated since firtool 1.57.0, has no effect (deduplication is always enabled), and will be removed in firtool 1.58.0
Users/schuylereldridge/repos/github.com/seldridge/scala-snippets/BoringUtils.scala:12:25: error: port "bore_ready" not fully initialized in module "Bar"
```

### PR DESCRIPTION
**Pull request by debs-sifive**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Bugfix
- Internal or build-related (includes code refactoring/cleanup)

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).

#### Release Notes

Coerces tapAndRead to punch stripped-direction flips when punching downwards with Inward non-probe ports, Fixes #3556 

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x`, `3.6.x`, or `5.x` depending on impact, API modification or big change: `6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

File: src/test/scala/chiselTests/BoringUtilsTapSpec.scala [hunk 1]
```diff
@@ -425,4 +425,75 @@ class BoringUtilsTapSpec extends ChiselFlatSpec with ChiselRunners with Utils wi
...
+    import chisel3.util.{Decoupled, DecoupledIO}
+    class Bar(b: DecoupledIO[Bool]) extends RawModule {
+      BoringUtils.tapAndRead(b)
+    }
+
+    class Foo extends RawModule {
+      val a = WireInit(DecoupledIO(Bool()), DontCare)
+      val dummyA = Wire(Output(chiselTypeOf(a)))
+      // FIXME we shouldn't need this intermediate wire
+      // https://github.com/chipsalliance/chisel/issues/3556
```
Comment (mwachs5) [inline src/test/scala/chiselTests/BoringUtilsTapSpec.scala:475]:
```suggestion
```
this PR is fixing 3556

**Comment by mwachs5** [comment]
Fixes https://github.com/chipsalliance/chisel/issues/3556

**Review by mwachs5 — APPROVED** [review]

**Comment by mwachs5** [comment]
what milestone should this be? 6.0?
