### PR TITLE
Fix 0 width signals chiselsim

### LINKED ISSUE #4099: ChiselSim fails to simulate circuit with optional (0-width) ports
**Type of issue**: Bug Report

**Please provide the steps to reproduce the problem:**

ChiselSim fails to simulate a circuit with optional `zero-width` signals, the following error is returned by verilator:

```
....
%Error: testbench.sv:10:19: Can't find definition of 'foo' in dotted variable: 'dut.foo'
   10 |   reg  [$bits(dut.foo)-1:0] foo;
      |                   ^~~
%Error-PINNOTFOUND: testbench.sv:23:6: Pin not found: 'foo'
...
```

This fails since the top `testbench.sv` file generated by [simulator/package.scala](https://github.com/chipsalliance/chisel/blob/151d63bb110b8939424a8c5e5746b9889b244a30/src/main/scala/chisel3/simulator/package.scala#L95) instantiates leaf ports without checking their width. On the other hand, firtool optimizes 0-width signals. Therefore, `testbench.sv` tries to access non-existing ports of the given dut and verilator raises the compilation error.

To reproduce the error I created a simple example [zero-width-verilator-err.zip](https://github.com/chipsalliance/chisel/files/15442208/zero-width-verilator-err.zip) that can be run through `scala-cli test zero-width-verilator-err.test.scala`.

A simple check of the port width during module elaboration in ChiselSim to prevent their instantiation" is sufficient to fix the error.
https://github.com/rameloni/chisel/blob/d8ba1b9d99c36e758d852d01cff26f1e9601e574/src/main/scala/chisel3/simulator/package.scala#L178-L185

### PR DESCRIPTION
**Pull request by rameloni**
Fixes #4099 

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Bugfix

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).

#### Release Notes

Fix failing ChiselSim/SVsim error to simulate modules with zero-width ports.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.6.x`, `5.x`, or `6.x` depending on impact, API modification or big change: `7.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Review by sequencer — APPROVED** [review]
LGTM

File: src/main/scala/chisel3/simulator/package.scala [hunk 1]
```diff
@@ -175,12 +175,14 @@ package object simulator {
...
             case element: Element =>
-              DataMirror.directionOf(element) match {
+              val _p = DataMirror.directionOf(element) match {
                 case ActualDirection.Input =>
                   Seq((element, ModuleInfo.Port(name, isGettable = true, isSettable = true)))
                 case ActualDirection.Output => Seq((element, ModuleInfo.Port(name, isGettable = true)))
                 case _                      => Seq()
               }
+              // Return the port only if the width is positive (firtool will optimized it out from the *.sv primary source)
+              if (element.widthKnown && element.getWidth > 0) _p else Seq()
```
Comment (jackkoenig) [inline src/main/scala/chisel3/simulator/package.scala:185]:
```suggestion
              // Return the port only if the width is positive (firtool will optimized it out from the *.sv primary source)
              if (element.widthKnown && element.getWidth > 0) {
                DataMirror.directionOf(element) match {
                  case ActualDirection.Input =>
                    Seq((element, ModuleInfo.Port(name, isGettable = true, isSettable = true)))
                  case ActualDirection.Output => Seq((element, ModuleInfo.Port(name, isGettable = true)))
                  case _                      => Seq()
                }
              } else {
                Seq()
              }
```
Better to not bother running the logic to generate the Port info if we don't need to.

File: src/test/scala/chiselTests/simulator/OptionalIOModule.scala [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+  out := myReg
+
+  when(a && b && c) {
+    myReg := foo
+  }
+  when(d && e && f) {
+    myReg := bar
+  }
+
+  printf(p"$a, $b, $c, $foo, $out\n")
```
Comment (jackkoenig) [inline src/test/scala/chiselTests/simulator/OptionalIOModule.scala:24]:
```suggestion
```
Please no `printf` in tests as they just pollute the console when running them

File: src/test/scala/chiselTests/simulator/SimulatorSpec.scala [hunk 3]
```diff
@@ -158,5 +159,80 @@ class SimulatorSpec extends AnyFunSpec with Matchers {
...
+      val width = 0
+      // Run a simulation with zero width foo
+      new VerilatorSimulator("test_run_dir/simulator/foo_zero_width") {
+        override val firtoolArgs = Seq("--strip-debug-info", "-g")
+      }
+        .simulate(new OptionalIOModule(n = width)) { module =>
+          import PeekPokeAPI._
+          val dut = module.wrapped
+          println("a, b, c, foo, out")
+          println("=================")
```
Comment (jackkoenig) [inline src/test/scala/chiselTests/simulator/SimulatorSpec.scala:172]:
```suggestion
```

File: src/test/scala/chiselTests/simulator/SimulatorSpec.scala [hunk 4]
```diff
@@ -158,5 +159,80 @@ class SimulatorSpec extends AnyFunSpec with Matchers {
...
+      val width = 8
+      // Run a simulation with zero width foo
+      new VerilatorSimulator("test_run_dir/simulator/foo_non_zero_width") {
+        override val firtoolArgs = Seq("--strip-debug-info", "-g")
+      }
+        .simulate(new OptionalIOModule(n = width)) { module =>
+          import PeekPokeAPI._
+          val dut = module.wrapped
+          println("a, b, c, foo, out")
+          println("=================")
```
Comment (jackkoenig) [inline src/test/scala/chiselTests/simulator/SimulatorSpec.scala:210]:
```suggestion
```

**Review by jackkoenig — APPROVED** [review]
Some minor nits but LGTM!
