### PR TITLE
Fix layer.enable applying to all later modules

### LINKED ISSUE #4839: `layer.enable` incorrectly applies to submodules
Consider the following:

``` scala
//> using scala "2.13.16"
//> using repository sonatype-s01:snapshots
//> using dep "org.chipsalliance::chisel::7.0.0-M2+599-7965f8e4-SNAPSHOT"
//> using plugin "org.chipsalliance:::chisel-plugin::7.0.0-M2+599-7965f8e4-SNAPSHOT"
//> using options "-unchecked", "-deprecation", "-language:reflectiveCalls", "-feature", "-Xcheckinit", "-Xfatal-warnings", "-Ywarn-dead-code", "-Ywarn-unused", "-Ymacro-annotations"

import chisel3._
import circt.stage.ChiselStage

class Bar extends RawModule

class Foo extends RawModule {

  layer.enable(layers.Verification)

  val b = Module(new Bar)

}

object Main extends App {

  println(
    ChiselStage.emitCHIRRTL(new Foo)
  )

}
```

This produces the following FIRRTL:

``` firrtl
FIRRTL version 4.2.0
circuit Foo :
  layer Verification, bind, "verification" :
    layer Assert, bind, "verification/assert" :
    layer Assume, bind, "verification/assume" :
    layer Cover, bind, "verification/cover" :

  module Bar enablelayer Verification :

    skip


  public module Foo enablelayer Verification :

    inst b of Bar
```

`module Bar` should not have the `Verification` layer enabled.

While this should be harmless, it can cause errors if combined with `ModuleChoice` and external modules. This can then create multiple instance choices which have different layers enabled (because external modules cannot have layers enabled). This then results in CIRCT catching the problem: https://github.com/llvm/circt/issues/8353

### PR DESCRIPTION
**Pull request by seldridge**
Fix a bug where use of the `layer.enable` API would incorrect cause a propagation of layers being enabled to all subsequent modules.  This was due to a bug in how the state save/restore logic worked.

Fixes #4839.

#### Release Notes

Fix a bug where `layer.enable` would apply to all later modules.

### CODE REVIEW

**Review by jackkoenig — APPROVED** [review]

File: src/test/scala-2/chiselTests/LayerSpec.scala [hunk 1]
```diff
@@ -216,6 +216,23 @@ class LayerSpec extends AnyFlatSpec with Matchers with FileCheck {
...
+  they should ", when enabled, not propagate to child modules" in {
+
+    class Bar extends RawModule
+
+    class Foo extends RawModule {
+      layer.enable(A)
+      val bar = Module(new Bar)
+    }
+
+    ChiselStage.emitCHIRRTL(new Foo, Array("--full-stacktrace")).fileCheck() {
```
Comment (jackkoenig) [inline src/test/scala-2/chiselTests/LayerSpec.scala:228]:
```suggestion
    ChiselStage.emitCHIRRTL(new Foo).fileCheck() {
```
Unnecessary (but benign) argument.

**Review by rwy7 — APPROVED** [review]

File: src/test/scala-2/chiselTests/LayerSpec.scala (hunk 1 above)
Comment (seldridge) [reply src/test/scala-2/chiselTests/LayerSpec.scala]: Thanks for catching this! I don't like when these stay in the tests. Fixed in: https://github.com/chipsalliance/chisel/pull/4840/commits/607aa6daf6a89764463f08933e9665956e8ea182
